### ISSUE TITLE
python3.9 设置function_timeout 引发异常

### ISSUE THREAD

**Issue by dragonsun7** [ydf0509/distributed_framework#37]
简单的试用了一下，发现指定了 `function_timeout` 参数后，程序会触发异常，如果不指定这个参数就正常。直接上代码：

**目录结构：**
```bash
├── consumer.py
├── distributed_frame_config.py
├── funcs.py
├── producer.py
```

**funcs.py**
```Python
import time

from function_scheduling_distributed_framework import task_deco, BrokerEnum


@task_deco('queue1', qps=3, broker_kind=BrokerEnum.RABBITMQ_AMQPSTORM, is_show_message_get_from_broker=True,
           is_using_distributed_frequency_control=True, function_timeout=600)
def task_fun(x, y):
    print(f'{x} + {y} = {x + y}')
    time.sleep(3)
```

**consumer.py**
```Python
from funcs import task_fun

if __name__ == '__main__':
    task_fun.consume()
```

**producer.py**
```Python
from funcs import task_fun

if __name__ == '__main__':
    for i in range(20):
        task_fun.push(i, i * 2)
```

**错误日志**
```Python
 (10.8.0.2,dm.local)-[p7047_t123145617371136] 2021-11-14 19:35:13 - RabbitmqConsumerAmqpStorm--queue1 - "base_consumer.py:554" - DEBUG - 从 rabbitmq 中间件 的 queue1 中取出的消息是 {"x": 9, "y": 18, "extra": {"task_id": "queue1_result:bcaeff96-d55d-494b-913c-a6e99ad1135b", "publish_time": 1636889710.6115, "publish_time_format": "2021-11-14 19:35:10"}}
2021-11-14 19:35:13 - _CustomThread - "/Users/替换后的路径/venv/lib/python3.9/site-packages/function_scheduling_distributed_framework/concurrent_pool/custom_threadpool_executor.py:172" - run - DEBUG - 新启动线程 123146003529728 
19:35:13  "/Users/替换后的路径/funcs.py:13"   9 + 18 = 27
 (10.8.0.2,dm.local)-[p7047_t123145734897664] 2021-11-14 19:35:14 - RabbitmqConsumerAmqpStorm--queue1 - "base_consumer.py:660" - ERROR - 函数 task_fun  第1次运行发生错误，函数运行时间是 3.0011 秒,
  入参是  {'x': 1, 'y': 2}    
 原因是 <class 'AttributeError'> '__KThread' object has no attribute 'isAlive' 
Traceback (most recent call last):
  File "/Users/替换后的路径/venv/lib/python3.9/site-packages/function_scheduling_distributed_framework/consumers/base_consumer.py", line 639, in _run_consuming_function_with_confirm_and_retry
    function_result_status.result = function_run(**function_only_params)
  File "/Users/替换后的路径/venv/lib/python3.9/site-packages/function_scheduling_distributed_framework/utils/decorators.py", line 539, in _
    alive = thd.isAlive()
AttributeError: '__KThread' object has no attribute 'isAlive'
```

**Comment by ydf0509** [comment]
我试试

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/141759979-58fe64c9-b649-4e6a-9883-ddcbe455e3a6.png)
这个属性被官方移除了，你搜搜is_alive

**Comment by dragonsun7** [comment]
是的，Python 3.9 的 `threading.Thread` 改成 `is_alive()` 了
将包中 `utils/decorators.py` 第539行改为 `alive = thd.is_alive()` 后运行正常。
