### ISSUE TITLE
运行时，报错TypeError: attrs() got an unexpected keyword argument 'eq'

### ISSUE THREAD

**Issue by hnwlxywns** [ydf0509/distributed_framework#8]
运行程序为：
`
@task_deco('ocr_content_and_audit', broker_kind=BrokerEnum.LOCAL_PYTHON_QUEUE, concurrent_mode=ConcurrentModeEnum.THREADING, qps=10)
def test_multi_thread_ocr(x):
     xxx

if __name__ == '__name__':
    for i in range(10):
        test_multi_thread_ocr(i)
    run_consumer_with_multi_process(test_multi_thread_ocr, 10)
`
运行日志如下：
`
15:33:41  "/usr/local/lib/python3.6/dist-packages/function_scheduling_distributed_framework-9.4-py3.6.egg/function_scheduling_distributed_framework/utils/decorators.py:28"    操作系统类型是  posix
 Traceback (most recent call last):
  File "AuditEngineScheduler.py", line 6, in <module>
    from function_scheduling_distributed_framework import task_deco, BrokerEnum, ConcurrentModeEnum, run_consumer_with_multi_process
  File "/usr/local/lib/python3.6/dist-packages/function_scheduling_distributed_framework-9.4-py3.6.egg/function_scheduling_distributed_framework/__init__.py", line 9, in <module>
    from function_scheduling_distributed_framework.consumers.base_consumer import ExceptionForRequeue, ExceptionForRetry, \
  File "/usr/local/lib/python3.6/dist-packages/function_scheduling_distributed_framework-9.4-py3.6.egg/function_scheduling_distributed_framework/consumers/base_consumer.py", line 49, in <module>
    from function_scheduling_distributed_framework.factories.publisher_factotry import get_publisher
  File "/usr/local/lib/python3.6/dist-packages/function_scheduling_distributed_framework-9.4-py3.6.egg/function_scheduling_distributed_framework/factories/publisher_factotry.py", line 16, in <module>
    from function_scheduling_distributed_framework.publishers.rabbitmq_pika_publisher import RabbitmqPublisher
  File "/usr/local/lib/python3.6/dist-packages/function_scheduling_distributed_framework-9.4-py3.6.egg/function_scheduling_distributed_framework/publishers/rabbitmq_pika_publisher.py", line 6, in <module>
    from pikav0 import BasicProperties
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/pikav0-0.1.2b0-py3.6.egg/pikav0/__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/pikav0-0.1.2b0-py3.6.egg/pikav0/adapters/__init__.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/pikav0-0.1.2b0-py3.6.egg/pikav0/adapters/twisted_connection.py", line 16, in <module>
  File "/usr/local/lib/python3.6/dist-packages/Twisted-21.2.0-py3.6.egg/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python3.6/dist-packages/Twisted-21.2.0-py3.6.egg/twisted/internet/default.py", line 55, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-21.2.0-py3.6.egg/twisted/internet/default.py", line 43, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/local/lib/python3.6/dist-packages/Twisted-21.2.0-py3.6.egg/twisted/internet/epollreactor.py", line 19, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python3.6/dist-packages/Twisted-21.2.0-py3.6.egg/twisted/internet/posixbase.py", line 20, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python3.6/dist-packages/Twisted-21.2.0-py3.6.egg/twisted/internet/udp.py", line 57, in <module>
    from twisted.internet import base, defer, address
  File "/usr/local/lib/python3.6/dist-packages/Twisted-21.2.0-py3.6.egg/twisted/internet/base.py", line 38, in <module>
    from twisted.internet._resolver import (
  File "/usr/local/lib/python3.6/dist-packages/Twisted-21.2.0-py3.6.egg/twisted/internet/_resolver.py", line 33, in <module>
    from twisted.internet.address import IPv4Address, IPv6Address
  File "/usr/local/lib/python3.6/dist-packages/Twisted-21.2.0-py3.6.egg/twisted/internet/address.py", line 99, in <module>
    @attr.s(hash=False, repr=False, eq=False)
TypeError: attrs() got an unexpected keyword argument 'eq'
`
请教一下这个是什么问题？

**Comment by ydf0509** [comment]
升级attrs包，pip install attrs --upgrade
